CREATE TABLE "site_drafts" (
	"id" text PRIMARY KEY NOT NULL,
	"company_id" text NOT NULL,
	"layout_global" jsonb DEFAULT '{"header":{"backgroundAndEffect":{"color":"#ffffff","opacity":0.95,"blur":10},"textColors":{"logo":"#000000","links":"#333333","hover":"#000000"},"actionButtons":{"backgroundColor":"#000000","textColor":"#ffffff"}},"typography":{"headingsFont":"Inter","subheadingsFont":"Inter","bodyFont":"Inter"},"siteColors":{"primary":"#000000","secondary":"#333333","background":"#ffffff"},"footer":{"colors":{"background":"#f5f5f5","text":"#333333","icons":"#000000"},"typography":{"headings":"Inter","body":"Inter"},"visibility":true}}'::jsonb NOT NULL,
	"home" jsonb DEFAULT '{"heroBanner":{"visibility":true,"title":{"text":"Sua beleza, nossa prioridade","color":"#000000","font":"Inter","sizeMobile":"32px","sizeDesktop":"48px"},"subtitle":{"text":"Agende seu horário e realce o que você tem de melhor","color":"#666666","font":"Inter","size":"18px"},"ctaButton":{"text":"Agendar Agora","backgroundColor":"#000000","textColor":"#ffffff","borderRadius":"8px","borderColor":"transparent","destinationLink":"/agendamento"},"appearance":{"bgType":"image","backgroundColor":"#ffffff","backgroundImageUrl":"","glassEffect":{"active":false,"intensity":0},"overlay":{"color":"#000000","opacity":0},"verticalAlignment":"center","horizontalAlignment":"center","sectionHeight":"medium"},"bgColor":"#ffffff"},"servicesSection":{"visibility":true,"orderOnHome":1,"header":{"title":{"text":"Nossos Serviços","color":"#000000","font":"Inter","size":"36px"},"subtitle":{"text":"Escolha o tratamento ideal para si","color":"#666666","font":"Inter","size":"16px"},"alignment":"center"},"cardConfig":{"showImage":true,"showCategory":true,"priceStyle":{"visible":true,"color":"#000000","font":"Inter"},"durationStyle":{"visible":true,"color":"#666666"},"cardBackgroundColor":"#ffffff","borderAndShadow":{"borderSize":"1px","shadowIntensity":"small"},"borderRadius":"12px"},"bookingButtonStyle":{"text":"Agendar","backgroundColor":"#000000","textColor":"#ffffff","borderRadius":"6px"}},"valuesSection":{"visibility":true,"orderOnHome":2,"header":{"title":{"text":"Nossos Valores","color":"#000000","font":"Inter","size":"36px"},"subtitle":{"text":"O que nos move todos os dias","color":"#666666","font":"Inter","size":"16px"}},"itemsStyle":{"layout":"grid","itemBackgroundColor":"#f9f9f9","borderRadius":"8px","internalAlignment":"center"},"items":[]},"galleryPreview":{"visibility":true,"orderOnHome":3,"header":{"title":{"text":"Nossa Galeria","color":"#000000","font":"Inter","size":"36px"},"subtitle":{"text":"Confira nossos últimos trabalhos","color":"#000000","font":"Inter","size":"16px"}},"galleryStyle":{"layout":"grid","cardRadius":"8px"}},"ctaSection":{"visibility":true,"title":{"text":"Agende agora mesmo","color":"#000000","font":"Inter","size":"32px"},"subtitle":{"text":"Entre em contato e reserve seu horário","color":"#666666","font":"Inter","size":"16px"},"button":{"text":"Agendar","backgroundColor":"#000000","textColor":"#ffffff","borderRadius":"8px","destinationLink":"/agendamento"},"background":{"type":"solid","color":"#f9f9f9","imageUrl":""}},"contactSection":{"visibility":true,"title":{"text":"Fale Conosco","color":"#000000","font":"Inter","size":"32px"},"subtitle":{"text":"Estamos prontos para te atender","color":"#666666","font":"Inter","size":"16px"},"button":{"text":"WhatsApp","backgroundColor":"#25D366","textColor":"#ffffff","borderRadius":"8px","destinationLink":"https://wa.me/00000000000"},"background":{"type":"solid","color":"#ffffff","imageUrl":""}}}'::jsonb NOT NULL,
	"gallery" jsonb DEFAULT '{"gridConfig":{"columns":3,"gap":"24px"},"interactivity":{"enableLightbox":true,"showCaptions":true}}'::jsonb NOT NULL,
	"about_us" jsonb DEFAULT '{"aboutBanner":{"visibility":true,"title":"Sobre Nós","backgroundImageUrl":""},"ourStory":{"visibility":true,"title":"Nossa História","text":"Começamos com um sonho...","imageUrl":""},"ourValues":[],"ourTeam":[],"testimonials":[]}'::jsonb NOT NULL,
	"appointment_flow" jsonb DEFAULT '{"colors":{"primary":"#000000","secondary":"#333333","background":"#ffffff","text":"#000000"},"step1Services":{"title":"Selecione o Serviço","showPrices":true,"showDurations":true,"cardConfig":{"backgroundColor":"TRANSPARENT_DEFAULT"}},"step2Date":{"title":"Escolha a Data","calendarStyle":"modern"},"step3Times":{"title":"Escolha o Horário","timeSlotStyle":"grid","timeSlotSize":30},"step4Confirmation":{"title":"Confirme seu Agendamento","requireLogin":false}}'::jsonb NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "site_drafts_company_id_unique" UNIQUE("company_id")
);
--> statement-breakpoint
ALTER TABLE "site_drafts" ADD CONSTRAINT "site_drafts_company_id_companies_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE cascade ON UPDATE no action;
