POST http://localhost:3001/api/billing
Content-Type: application/json

{
  "billingType": "PIX",
  "value": 100,
  "dueDate": "2026-12-01",
  "user": {
    "name": "Maciel Teste",
    "email": "[EMAIL_ADDRESS]",
    "document": "207.137.450-96",
    "mobilePhone": "11999999999"
  },
  "creditCard": {
    "holderName": "Maciel Teste",
    "number": "4111111111111112",
    "expiryMonth": "12",
    "expiryYear": "2026",
    "cvv": "123"
  },
  "address": {
    "postalCode": "01001-000",
    "addressNumber": "123",
    "addressComplement": "Apto 123",
    "phone": "11999999999"
  }
}